server :
  port : 8100

spring :
  application :
    name : novel-service

  profiles :
    active : dev

  config:
    import: optional:configserver:http://localhost:9200

    discsovery:
      enabled : false

service :
  api-gateway : api-gateway