server :
  port : 8100

eureka :
  client :
    service-url :
      default-zone : http://localhost:8761/eureka/

gateway :
  name : api-gateway

spring :
  application :
    name : novel-service

  profiles :
    include :
      - database
      - app

logging :
  level :
    root : #debug
