server :
  port : 9000

logging :
  level  :
    root : #debug


eureka :
  client :
    service-url :
      default-zone : http://localhost:8761/eureka/

spring :
  application :
    name : api-gateway

  profiles :
    include :
      - gateway

app:
  auth :
    secretKey : saedklawsekl
    tokenHeaderName : Authorization